services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=big
      - MYSQL_USER=sa
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

